### PR TITLE
Create ValueObject to encapsulate comparison between value objects

### PR DESCRIPTION
**Pull request by relaxdiego**
Learned about this project when I came across your Denver talk posted on Vimeo. Kudos for doing this! Here's my way of thanking you. :-)

This should DRY up value objects in the domain such that we don’t have to hand code equality methods in them. Other checks can be added later such as checking if ‘other’ is actually the same class.

### CODE REVIEW

**Comment by paulrayner** [comment]
This is excellent! BIG thanks. This is a great logical next step for the sample. 

One question: Itinerary is composed of an ordered set of Legs, so for two Itineraries to be equal, their Legs must be equal too. So does the equality logic in ValueObject handle this (common) kind of situation?

**Comment by relaxdiego** [comment]
No problem! I had fun writing that. 

Re: your question, it should just work since Array#== just compares each element with its corresponding element in the other array (http://www.ruby-doc.org/core-1.9.3/Array.html#method-i-3D-3D) and since we've already overridden Leg#== to work according to how we want it to work, then Itinerary#== should work as expected too.

**Comment by paulrayner** [comment]
Done! :beers: If you found the app through the Denver talk then you might not have seen http://thepaulrayner.com/blog/2013/06/20/domain-driven-design-in-ruby-at-ddd-exchange/. Thanks again...this is a great way to DRY things up.

**Comment by relaxdiego** [comment]
Thanks! I actually saw your blog post first which led me to the video. Good stuff. Looking forward to your updates. :-)

**Pull request merged**
